Repository OneulUi/client, pull requests merged in 2024-05, with the labels that each got.

#20 Feat: 렌딩페이지 추가
  api/api.ts
  api/axios.ts
  app/layout.tsx
  app/location/page.tsx
  app/ootd/write/page.tsx
  app/page.tsx
  app/signin/page.tsx
  app/survey/page.tsx
  assets/bg.png
  components/hook/uplodImg.tsx
  components/hook/useGetSurvey.tsx
  components/hook/useGetWeather.tsx
  components/ootd/WriteOotd.tsx
  components/ootd/write/SatisfyOotd.tsx
  components/react-query/Providers.tsx
  package-lock.json
  package.json
Labels: ☀️ Feat

#21 Feat: Google로그인 구현
  api/api.ts
  app/login/redirect/page.tsx
  app/page.tsx
  app/signin/page.tsx
  app/survey/page.tsx
  components/hook/useGetSurvey.tsx
  components/hook/useGetWeather.tsx
  components/hook/useGetWeather2.tsx
  next.config.mjs
Labels: bug, ☀️ Feat

#26 Fix: 컴포넌트 구조변경
  api/axios.ts
  app/location/page.tsx
  app/login/redirect/page.tsx
  app/ootd/write/page.tsx
  components/hook/uplodImg.tsx
  components/hook/usePostUsersPre.tsx
  components/ootd/write/HeaderWrite.tsx
  components/survey/SurveyComponent.tsx
Labels: ☀️ Feat

#27 Feat : Main 페이지 API 연동 및 필수 옷차림 페이지 구현
  app/main/page.tsx
  app/recommend/getup/page.tsx
  app/recommend/page.tsx
  components/main/Card.tsx
  components/main/TodayWeather.tsx
  components/main/WeatherByHour.tsx
  components/main/api.ts
  components/recommend/Eighth.tsx
  components/recommend/Fifth.tsx
  components/recommend/First.tsx
  components/recommend/Fourth.tsx
  components/recommend/Second.tsx
  components/recommend/Seventh.tsx
  components/recommend/Sixth.tsx
  components/recommend/Third.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: ☀️ Feat

#28 Feat: RenderingPage 완성, OOTD/WRITE props구현 완료
  app/ootd/write/page.tsx
  app/page.tsx
  app/signin/page.tsx
  assets/landingpicture.png
  assets/oneului.png
  components/ootd/write/SatisfyOotd.tsx
  components/ootd/write/Weather2.tsx
Labels: ☀️ Feat

#33 Refactor : 데이터가 들어오지 않을때 dummy 처리, 이미지 조회 테스트 완료
  app/ootd/page.tsx
  app/ootd/write/page.tsx
  assets/student.jpg
  components/ootd/UserComponent.tsx
  components/ootd/UserComponent2.tsx
  components/ootd/UserComponent3.tsx
  components/ootd/search/SearchComponent.tsx
  components/ootd/write/HeaderWrite.tsx
Labels: ☀️ Feat

#47 Feat : 마이페이지 api 연동
  app/mypage/edit/page.tsx
  app/mypage/likedootd/page.tsx
  app/mypage/myootd/page.tsx
  app/mypage/savedootd/page.tsx
  app/recommend/page.tsx
  components/main/WeatherByHour.tsx
  components/main/api.ts
  components/mypage/LikedOOTD.tsx
  components/mypage/MyOOTD.tsx
  components/mypage/MyProfile.tsx
  components/mypage/SavedOOTD.tsx
  components/mypage/api.ts
  components/recommend/Combination.tsx
  next.config.mjs
  utils/test.ts
Labels: ☀️ Feat

#49 Fix : api 오류 수정
  app/main/page.tsx
  app/recommend/page.tsx
  components/mypage/LikedOOTD.tsx
  components/mypage/MyOOTD.tsx
  components/mypage/MyProfile.tsx
  components/mypage/SavedOOTD.tsx
  components/recommend/Combination.tsx
Labels: bug
